### ISSUE TITLE
iOSとWebでは問題なく繋がるH.264の動画が落ちる

### ISSUE THREAD

**Issue by Masaki-U** [shiguredo/sora-android-sdk-samples#10]
概要
H.264でmomoから配信されている動画に繋ぐと、対応していないコーデックと言われ落ちる
詳細
momoから配信されているH.264の動画にiOSとWebは問題なく繋がりますが、
Androidでは対応していないビデオコーデックだとエラーが出て繋がりません。

同じ端末からVP8で配信するとAndroidも問題なく繋がるのですがのでコーデックが原因で落ちるようです。

検証端末
arroes F-02H Android 7.1.1
Xperia SO-01J Android 8.0.0

エラー部分のコード
```
2019-10-17 17:51:14.152 26494-27090/jp.shiguredo.sora.sample D/PeerChannelImpl: [rtc] @onSignalingChange: HAVE_REMOTE_OFFER
2019-10-17 17:51:14.152 26494-27089/jp.shiguredo.sora.sample I/channel.cc: (line 1061): Setting remote video description
2019-10-17 17:51:14.152 26494-27089/jp.shiguredo.sora.sample I/webrtc_video_engine.cc: (line 681): SetSendParameters: {codecs: [VideoCodec[120:H264], VideoCodec[96:rtx]], conference_mode: no, extensions: [{uri: http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time, id: 2}, {uri: urn:ietf:params:rtp-hdrext:sdes:mid, id: 9}, {uri: urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id, id: 13}, {uri: urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id, id: 14}], extmap-allow-mixed: false, max_bandwidth_bps: -1, mid: video_e5QIIE}
2019-10-17 17:51:14.152 26494-27089/jp.shiguredo.sora.sample E/webrtc_video_engine.cc: (line 621): No video codecs supported.
2019-10-17 17:51:14.152 26494-27090/jp.shiguredo.sora.sample E/peer_connection.cc: (line 5639): Failed to set remote video description send parameters. (INVALID_PARAMETER)
2019-10-17 17:51:14.153 26494-27090/jp.shiguredo.sora.sample E/peer_connection.cc: (line 2561): Failed to set remote offer sdp: Failed to set remote video description send parameters.
```

SDP
```
[signaling:DOWNSTREAM] <- offer
    v=0
    o=Shiguredo...Sora-19.04.9 8844107044210023783 0 IN IP4 0.0.0.0
    s=-
    t=0 0
    a=sendrecv
    a=fingerprint:sha-256
    a=group:BUNDLE video_i43jsi
    a=msid-semantic:WMS *
    a=ice-options:trickle
    m=video 9 UDP/TLS/RTP/SAVPF 120 96
    c=IN IP4 0.0.0.0
    a=candidate:0 1 UDP 2114002687 x.x.x.x 58698 typ host
    a=end-of-candidates
    a=sendonly
    a=rtcp-rsize
    a=rtcp-mux
    a=ice-ufrag:heKRr3Ug7OSs
    a=ice-pwd:42BPbSfBnpgWBWLy3EvtvtLX9gWjFXVY5iWe
    a=mid:video_i43jsi
    a=msid:e23aea57-0452-410b-8f86-92112fb9a6a7 46b1e34c-d4d1-4f05-a8d4-a0b05a46ed13
    a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
    a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
    a=extmap:13 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
    a=extmap:14 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
    a=rtpmap:120 H264/90000
    a=fmtp:120 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
    a=rtcp-fb:120 ccm fir
    a=rtcp-fb:120 nack
    a=rtcp-fb:120 nack pli
    a=rtpmap:96 rtx/90000
    a=fmtp:96 apt=120
    a=setup:actpass
    a=ssrc-group:FID 3187896557 901763305
    a=ssrc:3187896557 cname:
    a=ssrc:901763305 cname:
```

**Comment by voluntas** [comment]
@Masaki-U Web と Android で Sora を繋いだ場合は H.264 で動作していますでしょうか？

こちら、Android  端末のハードの問題で H.264 がうまく動作しないことがあるため、確認させていただいています。

**Comment by voluntas** [comment]
@Masaki-U Sora の最新版 19.10.0 でも同様の問題が発生するか確認をお願いできればと思います。

**Comment by Masaki-U** [comment]
返信ありがとうございます。

>Web と Android で Sora を繋いだ場合は H.264 で動作していますでしょうか？
>こちら、Android 端末のハードの問題で H.264 がうまく動作しないことがあるため、確認させていただいています。

はい、こちらAndroid端末のChromeでは問題なく動作することを確認しております。

>Sora の最新版 19.10.0 でも同様の問題が発生するか確認をお願いできればと思います。

こちらはサーバー担当の者に相談してみます。

**Comment by Masaki-U** [comment]
@voluntas 
>Sora の最新版 19.10.0 でも同様の問題が発生するか確認をお願いできればと思います。

こちら確認しましたところ、対応予定ではあるが昨日リリースされたばかりなのでまだ作業ははじめていない段階とのことでした。

**Comment by voluntas** [comment]
@Masaki-U 返信ありがとうございます。

説明が足りてなくて申し訳ありません。

Momo -> Sora -> Android SDK で動作しないとのことでしたが、
配信側を PC の Chrome に変更しての確認をお願いできますでしょうか。

PC の Chrome -> Sora -> Android SDK サンプルで H.264 では動作しますでしょうか？

確認のほどお願いいたします。

-- 

19.10.0 についてはまだ作業を始めてないとのことで了解しました。

**Comment by Masaki-U** [comment]
@voluntas 

>PC の Chrome -> Sora -> Android SDK サンプルで H.264 では動作しますでしょうか？

こちら再確認させてみましたがやはりH.264では繋がらず、
コーデックのみをVP8に変更したら繋がることを確認いたしました。

**Comment by voluntas** [comment]
@Masaki-U 確認ありがとうございます。 Chrome -> Sora -> Android SDK サンプルでつながらないということで、了解しました。

Chrome から送られてくる映像がダメというのはかなり珍しいパターンでして、おそらく端末依存かと考えております。社内では Pixel3 と Pixel3a でしか確認できてないため、このような報告大変ありがたいです。

---

こちらでも確認させていただきますので、以下をお教えいただければと思います。

- PC の OS (Windows, Linux, macOS)
- Chrome のバージョン
- 確認している Sora の機能や設定
  - おそらく片方向配信だと思いますが ...

（明日になってしまいますが）確認後、返信させていただきます。

**Comment by voluntas** [comment]
@Masaki-U arrows F-02H と Xperia SO-01J 以外の Android 端末では正常に動作していますでしょうか？

社内では Pixel3 / Pixel3a でのみ検証しております。

**Comment by Masaki-U** [comment]
@voluntas 
F-01H 5.1.1
SM-N950N 9.0.0
でも確認してみましたが同様の状態でした。

Pixel3 / Pixel3aは当社で保有しておりませんでした。

**Comment by Masaki-U** [comment]
@voluntas 
すみません見落としておりました。
>PC の OS (Windows, Linux, macOS)
macOSX Catalina最新版
>Chrome のバージョン
バージョン: 77.0.3865.120（Official Build） （64 ビット）
>確認している Sora の機能や設定
>おそらく片方向配信だと思いますが ...
御社のSora Demoの画面でわかる情報のみですが、
・ビデオのみ
・片方向配信
・サイマルキャストオフ
・VGA
・ビットレート500
になります。

サーバーの裏側で設定している情報については、
明日サーバー担当者に問い合わせてから改めて返信させていただきます。

**Comment by shino** [comment]
アプリケーションとしては、H.264 の視聴のみでしょうか。
その場合、一点試していただきたい設定がございます。

- Android アプリケーションの SoraMediaOption にエンコーダファクトリを設定する
- eglBaseContext は enableVideoDownstream に渡しているものと同じオブジェクトでOKです。

```
        mediaOption.videoEncoderFactory = HardwareVideoEncoderFactory(eglBaseContext, true, false)
```

以上、ご確認よろしくおねがいいたします。

**Comment by shino** [comment]
H.264 かつマルチストリーム無しの視聴のみで上記設定での動作は確認が取れていましたが、
VP8 や VP9 での端末互換性を考えると、次のコードのほうがより広い動作範囲となるため、
こちらで試してもらえますでしょうか。

```
        mediaOption.videoEncoderFactory = DefaultVideoEncoderFactory(eglBaseContext, true, false)
```

**Comment by Masaki-U** [comment]
@voluntas @shino 

>H.264 かつマルチストリーム無しの視聴のみで上記設定での動作は確認が取れていましたが、
VP8 や VP9 での端末互換性を考えると、次のコードのほうがより広い動作範囲となるため、
こちらで試してもらえますでしょうか。
```
 mediaOption.videoEncoderFactory = DefaultVideoEncoderFactory(eglBaseContext, true, false)
```

こちらで問題なく映りました！H.264もVP8もいけます！ありがとうございます！

```
mediaOption.videoEncoderFactory = HardwareVideoEncoderFactory(eglBaseContext, true, false)
```
こちらはVP8は映りませんでしたがH.264が動作することが確認できました！
当社はH.264で行くつもりなのでハードウェアアクセラレーションの効くこちらの設定で開発を進めようと思います。

重ね重ねありがとうございました！

**Comment by szktty** [comment]
@Masaki-U 本 issue への対応を含めた 1.10.0 をリリースしましたのでお知らせ致します。  mediaOption.videoEncoderFactory の指定は不要になります。特に何も設定しなくても H.264 で接続可能になります。

また何か問題がありましたらお知らせください。よろしくお願いします。
