### ISSUE TITLE
YUV <-> RGBの変換がおかしい

### ISSUE THREAD

**Issue by daneko** [shiguredo/sora-android-sdk-samples#3]
# 概要

* NV12 → RGB → NV12変換のなかで(おそらく)BRが入れ替わっている

## 詳細

SepiaFilterを足した場合にSepiaではなかったため、雑にあたりを付けてコードをいじっていたところ
[下記差分](https://github.com/shiguredo/sora-android-sdk-samples/compare/develop...daneko:workaround/fix-yuvrgb_convert?expand=1)で問題なく動作しているように見えます。

ただし、差分が正しいとすると、InもOutもNV21ということになり
org.webrtc.YuvHelper.I420ToNV12が21…？となり納得感がありません。

根本原因がわからないため、Issueとして上げておきます。

## workaround

https://github.com/shiguredo/sora-android-sdk-samples/compare/develop...daneko:workaround/fix-yuvrgb_convert?expand=1

## 検証端末

* SC-04J Android 8.0.0
* U11 Life Android 8.0.0
* Pixel Android 9

**Comment by shino** [comment]
問題の報告に加えて、修正案まで頂きありがとうございます。
確認いたします。

**Comment by shino** [comment]
#4 で問題を修正しました。
修正案ブランチにより、バグの絞り込みが楽になりました。ありがとうございました。

NV21/12 のあたりの話ですが、libyuv の RGB 系の扱いはメモリ上のバイト順序が逆になるところが(私には)ややこしいところでした。
https://chromium.googlesource.com/libyuv/libyuv/+/master/docs/formats.md#the-argb-fourcc

メモリ上、RGBA として扱いたいため、#4 では `I420ToABGR()` と `ABGRToI420()` を使うようにしています。

この issue はクローズとします。#4 の修正に問題などありましたら別途 issue を立ててもらえればと思います。
再度になりますが、ありがとうございました。
